name: Builds
on:
  push:
    branches: [master]
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - 'README*'
      - 'docs/**'
  pull_request:
    branches: [master]
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - 'README*'
      - 'docs/**'

defaults:
  run:
    # reference: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#using-a-specific-shell
    shell: bash --noprofile --norc -eo pipefail -x {0}

jobs:
  linux-build:
    runs-on: ubuntu-18.04
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: setup golang
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: install deps
      run: tests/scripts/helper.sh install_deps

    - name: setup minikube
      uses: manusa/actions-setup-minikube@v2.4.2
      with:
        minikube version: 'v1.21.0'
        kubernetes version: 'v1.19.2'
        start args: --memory 6g --cpus=2
        github token: ${{ secrets.GITHUB_TOKEN }}

    - name: build ceph-cosi
      run: |
        GOPATH=$(go env GOPATH) make clean && make build
        docker tag ceph-cosi-driver:latest ceph/ceph-cosi-driver:latest

    - name: setup ceph cluster
      run: tests/scripts/helper.sh setup_ceph_cluster

    - name: set up cosi
      run: |
        kubectl create -k github.com/kubernetes-sigs/container-object-storage-interface-api
        kubectl create -k github.com/kubernetes-sigs/container-object-storage-interface-controller
        kubectl create -k github.com/kubernetes-sigs/container-object-storage-interface-csi-adapter

    - name: set up ceph cosi driver
      run: |
        tests/scripts/helper.sh update_secret_file
        kubectl apply -k .

    - name: create bucket class and bucket request
      run: |
        kubectl create -f examples/bucketclass.yaml
        kubectl create -f examples/bucketrequest.yaml

    - name: create bucket access class and bucket access request
      run: |
        kubectl create -f examples/bucketaccessclass.yaml
        kubectl create -f examples/bucketrequest.yaml

    - name: setup tmate session for debugging
      if: failure()
      uses: mxschmitt/action-tmate@v3
      timeout-minutes: 120
